name: domotica_pro          # nivel 0
description: ...            # nivel 0
publish_to: 'none'         # nivel 0
version: 1.0.0+1          # nivel 0

environment:               # nivel 0
  sdk: '>=3.0.0 <4.0.0'   # nivel 2 espacios

dependencies:              # nivel 0 (IMPORTANTE: mismo nivel que flutter)
  flutter:                 # nivel 2 espacios
    sdk: flutter          # nivel 4 espacios
  shared_preferences: ^2.2.2  # nivel 2 espacios
  http: ^1.1.0            # nivel 2 espacios

dev_dependencies:          # nivel 0
  flutter_test:           # nivel 2 espacios
    sdk: flutter          # nivel 4 espacios

flutter:                   # nivel 0 (mismo nivel que dependencies)
  uses-material-design: true  # nivel 2 espacios
