name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Ver Flutter
        run: flutter --version

      - name: Instalar dependencias
        run: flutter pub get

      - name: Analizar proyecto
        run: flutter analyze

      - name: Compilar APK
        run: flutter build apk --release

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: barberpro-apk
          path: build/app/outputs/flutter-apk/app-release.apk
